# Generated by Django 3.2.8 on 2021-10-26 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('nacimiento', models.DateField(default=django.utils.timezone.now)),
                ('domicilio', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('hobbie1', models.TextField(max_length=100)),
                ('hobbie1description', models.TextField(max_length=100)),
                ('hobbie2', models.TextField(max_length=100)),
                ('hobbie2description', models.TextField(max_length=100)),
                ('hobbie3', models.TextField(max_length=100)),
                ('hobbie3description', models.TextField(max_length=100)),
                ('yo_soy', models.CharField(max_length=50)),
                ('yo_soydescription', models.TextField(max_length=500)),
                ('profesion', models.TextField(max_length=100)),
                ('experiencia', models.CharField(max_length=1000)),
                ('formacionAcademica', models.TextField(max_length=500)),
                ('cursos', models.TextField(max_length=1000)),
                ('telefono', models.PositiveIntegerField()),
                ('localidad', models.TextField(max_length=50)),
                ('webPage', models.CharField(max_length=100)),
                ('habilidades1', models.CharField(max_length=50)),
                ('habilidades2', models.CharField(max_length=50)),
                ('habilidades3', models.CharField(max_length=50)),
                ('habilidades4', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
