# Generated by Django 3.2.8 on 2021-10-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculumvitae', '0002_cv_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='sexo',
        ),
    ]
