# Generated by Django 3.2.8 on 2021-10-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculumvitae', '0003_remove_cv_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
