# Generated by Django 3.2.8 on 2021-10-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculumvitae', '0004_alter_cv_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='fotos',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
