# Generated by Django 3.2.8 on 2021-11-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculumvitae', '0005_cv_fotos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='hobbie1',
            new_name='description_hobbie_1',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='hobbie1description',
            new_name='description_hobbie_2',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='hobbie2',
            new_name='description_hobbie_3',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='hobbie2description',
            new_name='nombre_hobbie_1',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='hobbie3',
            new_name='nombre_hobbie_2',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='hobbie3description',
            new_name='nombre_hobbie_3',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='yo_soydescription',
            new_name='yo_soy_description',
        ),
    ]
