# Generated by Django 3.2.8 on 2021-11-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculumvitae', '0007_auto_20211101_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='nombre_habilidad1',
            new_name='nombre_habilidad_1',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='nombre_habilidad2',
            new_name='nombre_habilidad_2',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='nombre_habilidad3',
            new_name='nombre_habilidad_3',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='nombre_habilidad4',
            new_name='nombre_habilidad_4',
        ),
    ]
