# Generated by Django 3.2.8 on 2021-11-02 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculumvitae', '0009_trabajos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajos',
            old_name='descripción_trabajo',
            new_name='descripcion_trabajo',
        ),
    ]
